//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PECS2022.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PECS2022.Resources.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يجب ان يكون بالاحرف العربية فقط.
        /// </summary>
        public static string ArabicOnly {
            get {
                return ResourceManager.GetString("ArabicOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التلفون المطلوب في كل محاولة اتصال.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الاتصال.
        /// </summary>
        public static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تم الرد على الاتصال.
        /// </summary>
        public static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل المجيب رب الأسرة.
        /// </summary>
        public static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادون ]اسم الشخص[ ورقمه من كشف الأسرة.
        /// </summary>
        public static string C6 {
            get {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشخص اخرى.
        /// </summary>
        public static string C6_Name {
            get {
                return ResourceManager.GetString("C6_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل وافق ]....[ على إجراء المقابلة.
        /// </summary>
        public static string C7 {
            get {
                return ResourceManager.GetString("C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للباحث: الاستفسار من المبحوث عن إمكانية إعادة الاتصال به بوقت لاحق.
        /// </summary>
        public static string C8 {
            get {
                return ResourceManager.GetString("C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الاتصال.
        /// </summary>
        public static string C9 {
            get {
                return ResourceManager.GetString("C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الباحث.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم سطر الفرد.
        /// </summary>
        public static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل (الاسم ...) ملتحق بالتعليم؟.
        /// </summary>
        public static string D10 {
            get {
                return ResourceManager.GetString("D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي عدد سنوات الدراسة التي أتمها (الاسم ...) بنجاح في التعليم النظامي؟.
        /// </summary>
        public static string D11 {
            get {
                return ResourceManager.GetString("D11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو المستوى التعليمي (للاسم ...)؟.
        /// </summary>
        public static string D12 {
            get {
                return ResourceManager.GetString("D12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الاسباب التالية ما هو السبب الرئيسي الذي دفع (الاسم ...) لترك المدرسة.
        /// </summary>
        public static string D12_01 {
            get {
                return ResourceManager.GetString("D12_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخرى حدد.
        /// </summary>
        public static string D12_01_CMNT {
            get {
                return ResourceManager.GetString("D12_01_CMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تم الرسوب في  أي سنة دراسية من قبل (الاسم).
        /// </summary>
        public static string D12_02 {
            get {
                return ResourceManager.GetString("D12_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي علاقة (الاسم ...) بقوة العمل خلال الأسبوع الماضي؟.
        /// </summary>
        public static string D13 {
            get {
                return ResourceManager.GetString("D13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخرى حدد.
        /// </summary>
        public static string D13_CMNT {
            get {
                return ResourceManager.GetString("D13_CMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي الحالة العملية الرئيسة (للاسم ...)؟.
        /// </summary>
        public static string D14 {
            get {
                return ResourceManager.GetString("D14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو مكان عمل (الاسم ...)؟.
        /// </summary>
        public static string D15 {
            get {
                return ResourceManager.GetString("D15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل كان عمل (الاسم) في عمله الحالي او السابق على أساس عقد عمل ؟.
        /// </summary>
        public static string D15_1 {
            get {
                return ResourceManager.GetString("D15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي طبيعة دوام (الاسم) في عمله الحالي أو السابق.
        /// </summary>
        public static string D15_2 {
            get {
                return ResourceManager.GetString("D15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهنة الرئيسية الحالية/ السابقة.
        /// </summary>
        public static string D16 {
            get {
                return ResourceManager.GetString("D16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهنة الرئيسية الحالية/ السابقة.
        /// </summary>
        public static string D16_Desc {
            get {
                return ResourceManager.GetString("D16_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النشاط الاقتصادي الرئيسي الحالي/ السابق.
        /// </summary>
        public static string D17 {
            get {
                return ResourceManager.GetString("D17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النشاط الاقتصادي الرئيسي الحالي/ السابق.
        /// </summary>
        public static string D17_Desc {
            get {
                return ResourceManager.GetString("D17_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو القطاع الذي يعمل فيه (الاسم ...)؟.
        /// </summary>
        public static string D18 {
            get {
                return ResourceManager.GetString("D18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة.
        /// </summary>
        public static string D18_1 {
            get {
                return ResourceManager.GetString("D18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الذي يتقاضاه.
        /// </summary>
        public static string D18_2 {
            get {
                return ResourceManager.GetString("D18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العملة.
        /// </summary>
        public static string D18_3 {
            get {
                return ResourceManager.GetString("D18_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو مقدار الاجر الذي يتقاضاه (الاسم ...)؟.
        /// </summary>
        public static string D18X {
            get {
                return ResourceManager.GetString("D18X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يسأل للأفراد الذين أجابوا (1-4) في سؤال D13 وللخيارات الأخرى لا تتم إجابة السؤال ويترك فارغ  هل يزاول (الاسم ...) عمل ثانوي (عمل آخر)؟.
        /// </summary>
        public static string D19 {
            get {
                return ResourceManager.GetString("D19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كم شهراً عمل (الاسم) بانتظام خلال 12 شهر الماضية.
        /// </summary>
        public static string D19_1 {
            get {
                return ResourceManager.GetString("D19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل يقوم صاحب العمل بتوفير أي من الامتيازات التالية.
        /// </summary>
        public static string D19_2 {
            get {
                return ResourceManager.GetString("D19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساهمة في تمويل التقاعد/ مكافئة نهاية الخدمة.
        /// </summary>
        public static string D19_2_1 {
            get {
                return ResourceManager.GetString("D19_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منح إجازات سنوية مدفوعة او تعويض بدل إجازة.
        /// </summary>
        public static string D19_2_2 {
            get {
                return ResourceManager.GetString("D19_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . منح إجازة مرضية مدفوعة الأجر.
        /// </summary>
        public static string D19_2_3 {
            get {
                return ResourceManager.GetString("D19_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منح إجازة امومة مدفوعة (للنساء فقط).
        /// </summary>
        public static string D19_2_4 {
            get {
                return ResourceManager.GetString("D19_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكافأة نهاية خدمة.
        /// </summary>
        public static string D19_2_5 {
            get {
                return ResourceManager.GetString("D19_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الرباعي.
        /// </summary>
        public static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي الحالة الزواجية (للاسم...)؟.
        /// </summary>
        public static string D21 {
            get {
                return ResourceManager.GetString("D21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علاقة (الاسم ...) برب الأسرة.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو  جنس (الاسم ...).
        /// </summary>
        public static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو عمر (الاسم ...) بالسنوات الكاملة.
        /// </summary>
        public static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هي حالة اللجوء  (للاسم ...) .
        /// </summary>
        public static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل (الاسم...) لديه تامين صحي.
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى حدد.
        /// </summary>
        public static string D7_CMNT {
            get {
                return ResourceManager.GetString("D7_CMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل (الاسم) يعاني من أي مرض مزمن بحسب تشخيص طبي ويتلقى علاج بصورة مستمرة له؟ (سكري، ضغط دم، أمراض القلب، سرطان، قرحة ، ربو (أزمة)، صرع، أخرى).
        /// </summary>
        public static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البصر.
        /// </summary>
        public static string D9_A {
            get {
                return ResourceManager.GetString("D9_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السمع.
        /// </summary>
        public static string D9_B {
            get {
                return ResourceManager.GetString("D9_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة واستخدام الايدي.
        /// </summary>
        public static string D9_C {
            get {
                return ResourceManager.GetString("D9_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التذكر والتركيز.
        /// </summary>
        public static string D9_D {
            get {
                return ResourceManager.GetString("D9_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التواصل.
        /// </summary>
        public static string D9_E {
            get {
                return ResourceManager.GetString("D9_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرعاية الذاتية/ الشخصية.
        /// </summary>
        public static string D9_F {
            get {
                return ResourceManager.GetString("D9_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يجب ان يكون ارقام فقط.
        /// </summary>
        public static string DigitOnly {
            get {
                return ResourceManager.GetString("DigitOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التاكد من القيمة المدخلة.
        /// </summary>
        public static string GError {
            get {
                return ResourceManager.GetString("GError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاسرة المتسلسل في العينة.
        /// </summary>
        public static string ID00 {
            get {
                return ResourceManager.GetString("ID00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المحافظة.
        /// </summary>
        public static string ID1 {
            get {
                return ResourceManager.GetString("ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التجمع السكاني.
        /// </summary>
        public static string ID2 {
            get {
                return ResourceManager.GetString("ID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم منطقة العد.
        /// </summary>
        public static string ID3 {
            get {
                return ResourceManager.GetString("ID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تعداد المبنى في منطقة العد.
        /// </summary>
        public static string ID4 {
            get {
                return ResourceManager.GetString("ID4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوحدة السكنية في المبنى.
        /// </summary>
        public static string ID5 {
            get {
                return ResourceManager.GetString("ID5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الأسرة في عينة منطقة العد.
        /// </summary>
        public static string ID6 {
            get {
                return ResourceManager.GetString("ID6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الأسرة في عينة منطقة العد.
        /// </summary>
        public static string ID6_Desc {
            get {
                return ResourceManager.GetString("ID6_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الوحدة السكنية من المنطقة العازلة/ من جدار الضم والتوسع.
        /// </summary>
        public static string ID7 {
            get {
                return ResourceManager.GetString("ID7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الوحدة السكنية من المنطقة العازلة/ من جدار الضم والتوسع.
        /// </summary>
        public static string ID7_Desc {
            get {
                return ResourceManager.GetString("ID7_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم حسب الكشف.
        /// </summary>
        public static string IndivID {
            get {
                return ResourceManager.GetString("IndivID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string IndivName {
            get {
                return ResourceManager.GetString("IndivName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن  اختيار هذه القيمة.
        /// </summary>
        public static string InValidValue {
            get {
                return ResourceManager.GetString("InValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى لعدد حروف الحقل {0}  هو {1} حرفا.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة المقابلة.
        /// </summary>
        public static string QC2 {
            get {
                return ResourceManager.GetString("QC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات نتيجة المقابلة.
        /// </summary>
        public static string QC2_CMNT {
            get {
                return ResourceManager.GetString("QC2_CMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم رب الأسرة.
        /// </summary>
        public static string QC3_1 {
            get {
                return ResourceManager.GetString("QC3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تلفون أرضي.
        /// </summary>
        public static string QC3_2 {
            get {
                return ResourceManager.GetString("QC3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تلفون نقال.
        /// </summary>
        public static string QC3_3 {
            get {
                return ResourceManager.GetString("QC3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثلاثي.
        /// </summary>
        public static string QC4_1 {
            get {
                return ResourceManager.GetString("QC4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تلفون نقال.
        /// </summary>
        public static string QC4_2 {
            get {
                return ResourceManager.GetString("QC4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يجب ان تكون رقما  ما بين  {1} و {2} .
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} حقل متطلب.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقل {0} يجب ان يكون بين {1} و {2} حرف.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} يجب ان يكون 9  ارقام فقط ان يبدأ بأحد الارقام التالية (02,04,08,09) فقط.
        /// </summary>
        public static string TelFormat {
            get {
                return ResourceManager.GetString("TelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تلفون أرضي يجب ان يكون  ارقام فقط.
        /// </summary>
        public static string TELNotValid {
            get {
                return ResourceManager.GetString("TELNotValid", resourceCulture);
            }
        }
    }
}
